[package]
name = "l1_ir"
version = "0.0.11"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "L1 Intermediate Representation"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/L1IR"
keywords = ["compiler","interpreter","AST","IR","JIT"]

[dependencies]
num-bigint = { version = "0.4" }
cranelift = { version = "0.91", optional = true }
cranelift-module = { version = "0.91", optional = true }
cranelift-jit = { version = "0.91", optional = true }

[features]
cranelift = ["dep:cranelift", "dep:cranelift-module", "dep:cranelift-jit"]
