[package]
name = "l1_ir"
version = "0.0.7"
authors = ["Andrew <andrew@subarctic.org>"]
license = "MIT"
description = "L1 Intermediate Representation"
edition = "2018"
readme = "README.md"
repository = "https://github.com/andrew-johnson-4/L1IR"
keywords = ["compiler","interpreter","AST","IR","JIT"]

[dependencies]
cranelift = "0.91"
cranelift-module = "0.91"
cranelift-jit = "0.91"
